// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo_List_P6.Models;

#nullable disable

namespace Todo_List_P6.Migrations
{
    [DbContext(typeof(TodoAppContext))]
    partial class TodoAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Todo_List_P6.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Buy groceries",
                            isCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finish project report",
                            isCompleted = false
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Call mom",
                            isCompleted = true
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Go for a run",
                            isCompleted = false
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Read a book",
                            isCompleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
